export interface KfaMedication {
  kfaCode: string;
  name: string;
  genericName: string;
  form: string;
  strength: string;
  route: string;
  category: string;
  defaultDosage: string;
  defaultFrequency: string;
  defaultTiming: string;
  unit: string;
  indications: string[];
}

export const KFA_MEDICATIONS_DATABASE: KfaMedication[] = [
  {
    kfaCode: "93001027",
    name: "Paracetamol 500 mg Tablet",
    genericName: "Paracetamol",
    form: "Tablet",
    strength: "500 mg",
    route: "Oral",
    category: "Analgesik & Antipiretik",
    defaultDosage: "500 mg",
    defaultFrequency: "3x sehari 1 tablet",
    defaultTiming: "Sesudah makan (bila demam/nyeri)",
    unit: "Tablet",
    indications: ["Demam", "Nyeri Ringan hingga Sedang", "Sakit Kepala", "Myalgia"],
  },
  {
    kfaCode: "93000845",
    name: "Amlodipine 5 mg Tablet",
    genericName: "Amlodipine Besylate",
    form: "Tablet",
    strength: "5 mg",
    route: "Oral",
    category: "Antihipertensi (CCB)",
    defaultDosage: "5 mg",
    defaultFrequency: "1x sehari 1 tablet",
    defaultTiming: "Malam hari sesudah makan",
    unit: "Tablet",
    indications: ["Hipertensi Primer", "Angina Pektoris Stabil"],
  },
  {
    kfaCode: "93000846",
    name: "Amlodipine 10 mg Tablet",
    genericName: "Amlodipine Besylate",
    form: "Tablet",
    strength: "10 mg",
    route: "Oral",
    category: "Antihipertensi (CCB)",
    defaultDosage: "10 mg",
    defaultFrequency: "1x sehari 1 tablet",
    defaultTiming: "Malam hari sesudah makan",
    unit: "Tablet",
    indications: ["Hipertensi Derajat 2", "Angina Kronik"],
  },
  {
    kfaCode: "93001552",
    name: "Metformin HCl 500 mg Tablet",
    genericName: "Metformin Hydrochloride",
    form: "Tablet",
    strength: "500 mg",
    route: "Oral",
    category: "Antidiabetes Oral (Biguanid)",
    defaultDosage: "500 mg",
    defaultFrequency: "2x sehari 1 tablet",
    defaultTiming: "Bersama makanan atau sesaat setelah makan",
    unit: "Tablet",
    indications: ["Diabetes Melitus Tipe 2", "Resistensi Insulin"],
  },
  {
    kfaCode: "93001553",
    name: "Metformin HCl 850 mg Tablet",
    genericName: "Metformin Hydrochloride",
    form: "Tablet",
    strength: "850 mg",
    route: "Oral",
    category: "Antidiabetes Oral (Biguanid)",
    defaultDosage: "850 mg",
    defaultFrequency: "2x sehari 1 tablet",
    defaultTiming: "Bersama makanan utama",
    unit: "Tablet",
    indications: ["Diabetes Melitus Tipe 2"],
  },
  {
    kfaCode: "93000412",
    name: "Amoxicillin 500 mg Kapsul",
    genericName: "Amoxicillin Trihydrate",
    form: "Kapsul",
    strength: "500 mg",
    route: "Oral",
    category: "Antibiotik Penicilin",
    defaultDosage: "500 mg",
    defaultFrequency: "3x sehari 1 kapsul",
    defaultTiming: "Tiap 8 jam sesudah makan (Habiskan)",
    unit: "Kapsul",
    indications: ["ISPA Bakterial", "Faringitis Akut", "Otitis Media", "Infeksi Saluran Kemih"],
  },
  {
    kfaCode: "93001740",
    name: "Omeprazole 20 mg Kapsul Pelepasan Lambat",
    genericName: "Omeprazole",
    form: "Kapsul",
    strength: "20 mg",
    route: "Oral",
    category: "Antasida & Antisekresi Lambung (PPI)",
    defaultDosage: "20 mg",
    defaultFrequency: "1x sehari 1 kapsul",
    defaultTiming: "Pagi hari 30 menit sebelum sarapan",
    unit: "Kapsul",
    indications: ["GERD", "Gastritis Erosif", "Ulkus Peptikum", "Dispepsia Fungsional"],
  },
  {
    kfaCode: "93001890",
    name: "Captopril 25 mg Tablet",
    genericName: "Captopril",
    form: "Tablet",
    strength: "25 mg",
    route: "Oral",
    category: "Antihipertensi (ACE Inhibitor)",
    defaultDosage: "25 mg",
    defaultFrequency: "2x sehari 1 tablet",
    defaultTiming: "1 jam sebelum makan (saat lambung kosong)",
    unit: "Tablet",
    indications: ["Hipertensi", "Gagal Jantung Kongestif"],
  },
  {
    kfaCode: "93002130",
    name: "Cetirizine HCl 10 mg Tablet Salut Selaput",
    genericName: "Cetirizine Hydrochloride",
    form: "Tablet Salut Selaput",
    strength: "10 mg",
    route: "Oral",
    category: "Antihistamin Generasi 2",
    defaultDosage: "10 mg",
    defaultFrequency: "1x sehari 1 tablet",
    defaultTiming: "Malam hari sebelum tidur",
    unit: "Tablet",
    indications: ["Rinitis Alergi", "Urtikaria Kronis", "Alergi Makanan / Kontak"],
  },
  {
    kfaCode: "93002245",
    name: "Salbutamol 2 mg Tablet",
    genericName: "Salbutamol Sulfate",
    form: "Tablet",
    strength: "2 mg",
    route: "Oral",
    category: "Bronkodilator (Beta-2 Agonis)",
    defaultDosage: "2 mg",
    defaultFrequency: "3x sehari 1 tablet",
    defaultTiming: "Sesudah makan (bila sesak napas)",
    unit: "Tablet",
    indications: ["Asma Bronkial", "PPOK Eksaserbasi Akut", "Bronkospasme"],
  },
  {
    kfaCode: "93002380",
    name: "Azithromycin 500 mg Tablet Salut Selaput",
    genericName: "Azithromycin Dihydrate",
    form: "Tablet Salut Selaput",
    strength: "500 mg",
    route: "Oral",
    category: "Antibiotik Makrolida",
    defaultDosage: "500 mg",
    defaultFrequency: "1x sehari 1 tablet",
    defaultTiming: "1 jam sebelum atau 2 jam sesudah makan (selama 3-5 hari)",
    unit: "Tablet",
    indications: ["Pneumonia Komunitas", "Sinusitis Bakterial", "Faringitis Non-Streptokokus"],
  },
  {
    kfaCode: "93002610",
    name: "Simvastatin 20 mg Tablet Salut Selaput",
    genericName: "Simvastatin",
    form: "Tablet Salut Selaput",
    strength: "20 mg",
    route: "Oral",
    category: "Hipolipidemik (Statin)",
    defaultDosage: "20 mg",
    defaultFrequency: "1x sehari 1 tablet",
    defaultTiming: "Malam hari sebelum tidur sesudah makan",
    unit: "Tablet",
    indications: ["Hiperkolesterolemia Primer", "Dislipidemia Campuran", "Pencegahan Kardiovaskular"],
  },
  {
    kfaCode: "93002770",
    name: "Ibuprofen 400 mg Tablet Salut Selaput",
    genericName: "Ibuprofen",
    form: "Tablet Salut Selaput",
    strength: "400 mg",
    route: "Oral",
    category: "Antiinflamasi Non-Steroid (OAINS)",
    defaultDosage: "400 mg",
    defaultFrequency: "3x sehari 1 tablet",
    defaultTiming: "Wajib sesudah makan (bersama segelas air)",
    unit: "Tablet",
    indications: ["Nyeri Muskuloskeletal", "Artritis", "Dismenore", "Nyeri Pasca Tindakan"],
  },
  {
    kfaCode: "93002890",
    name: "Oralit Serbuk untuk Larutan Oral 200 ml",
    genericName: "Glucose, Sodium Chloride, Potassium Chloride, Trisodium Citrate",
    form: "Serbuk Larutan Oral",
    strength: "200 ml / sachet",
    route: "Oral",
    category: "Rehidrasi Cairan & Elektrolit",
    defaultDosage: "1 sachet dilarutkan dalam 200 ml air matang",
    defaultFrequency: "Tiap kali buang air besar cair",
    defaultTiming: "Minum perlahan sedikit demi sedikit",
    unit: "Sachet",
    indications: ["Diare Akut Dehidrasi Ringan-Sedang", "Pencegahan Dehidrasi"],
  },
  {
    kfaCode: "93003012",
    name: "Antasida Doen Tablet Kunyah",
    genericName: "Aluminium Hydroxide & Magnesium Hydroxide",
    form: "Tablet Kunyah",
    strength: "Al(OH)3 200 mg + Mg(OH)2 200 mg",
    route: "Oral",
    category: "Antasida Lambung",
    defaultDosage: "1-2 tablet",
    defaultFrequency: "3-4x sehari 1 tablet",
    defaultTiming: "Dikunyah 1 jam sebelum makan atau 2 jam setelah makan",
    unit: "Tablet Kunyah",
    indications: ["Nyeri Ulu Hati", "Kelebihan Asam Lambung", "Gastritis Akut"],
  }
];
