import { OutpatientEncounter, PatientProfile, ClinicQueuePatientItem } from "./types";

export const MOCK_PATIENT: PatientProfile = {
  id: "P-10002891902", // SATUSEHAT Patient ID
  nik: "3174051208820003",
  mrn: "RM-2026-08912",
  name: "Budi Santoso, S.Kom",
  gender: "male",
  birthDate: "1982-08-12",
  phone: "0812-8941-2099",
  address: "Jl. Margonda Raya No. 45, Beji, Kota Depok, Jawa Barat 16424",
  bloodType: "O",
  allergies: ["Penisilin (Gatal-gatal & Ruam Kulit)"],
  emergencyContact: {
    name: "Ratna Kusuma (Istri)",
    relation: "Istri",
    phone: "0813-7721-9988",
  },
  paymentPayer: "BPJS Kesehatan (JKN-PBI)",
  lastVisitDate: "2026-08-25",
  lastVisitDepartment: "Poli Penyakit Dalam",
  lastVisitDoctor: "dr. Rian Pratama, Sp.PD",
  lastVisitDiagnosis: "Hipertensi Primer (I10)",
  totalVisitsCount: 6,
  satusehatConsent: "opt-in",
};

export const MOCK_ENCOUNTERS: OutpatientEncounter[] = [
  {
    id: "ENC-20260902-0001",
    registrationNumber: "RJ-20260902-0001",
    patientId: "P-10002891902",
    satusehatEncounterId: "ss-enc-89210-9941a",
    visitDate: "2026-09-02T09:30:00+07:00",
    clinicDepartment: "Poli Penyakit Dalam",
    doctorName: "dr. Rian Pratama, Sp.PD",
    doctorSip: "SIP.446/089/DS/Dinkes/2026",
    doctorIhsId: "N10009841",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Sakit kepala di tengkuk belakang sejak 3 hari dan badan terasa cepat lelah",
    anamnesis:
      "Pasien datang dengan keluhan tegang dan pegal di bagian tengkuk leher belakang sejak 3 hari lalu. Tidak ada demam, tidak ada riwayat sesak napas. Pasien memiliki riwayat tensi batas atas dari pemeriksaan sebelumnya.",
    vitals: {
      systolic: 138,
      diastolic: 88,
      heartRate: 78,
      temperature: 36.6,
      respiratoryRate: 18,
      oxygenSaturation: 98,
      weightKg: 68,
      heightCm: 172,
      bmi: 23.0,
      physicalExamNotes:
        "Keadaan umum baik, compos mentis. Cor/Pulmo dalam batas normal. Abdomen supel, bising usus normal. Ekstremitas hangat, tidak ada edema.",
    },
    diagnoses: [
      {
        id: "diag-001-1",
        type: "primary",
        code: "I10",
        display: "Essential (primary) hypertension",
        patientFriendlyName: "Hipertensi Primer (Tekanan Darah Tinggi Tahap 1)",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
      {
        id: "diag-001-2",
        type: "secondary",
        code: "R53.83",
        display: "Other fatigue",
        patientFriendlyName: "Kelelahan Fisik Ringan",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-001-1",
        code: "89.07",
        display: "General medical consultation",
        category: "Konsultasi & Pemeriksaan Fisik",
        notes: "Konsultasi evaluasi kardiovaskular dan gaya hidup",
      },
      {
        id: "proc-001-2",
        code: "89.52",
        display: "Electrocardiogram",
        category: "Pemeriksaan Penunjang",
        notes: "EKG 12-Lead: Sinus ritme reguler, tidak ada tanda iskemia akut",
      },
    ],
    prescriptions: [
      {
        id: "med-001-1",
        kfaCode: "93000182",
        medicationName: "Amlodipine Besilate 5 mg",
        form: "Tablet",
        dosage: "5 mg",
        frequency: "1 x 1 tablet sehari",
        timing: "Sesudah Makan",
        schedule: {
          morning: false,
          afternoon: false,
          evening: false,
          night: true,
        },
        quantity: 30,
        unit: "Tablet",
        durationDays: 30,
        instructions: "Diminum 1 tablet tiap malam sebelum tidur sesudah makan.",
      },
      {
        id: "med-001-2",
        kfaCode: "93000401",
        medicationName: "Paracetamol 500 mg",
        form: "Kaplet",
        dosage: "500 mg",
        frequency: "3 x 1 kaplet sehari (Bila Perlu)",
        timing: "Sesudah Makan",
        schedule: {
          morning: true,
          afternoon: true,
          evening: true,
          night: false,
        },
        quantity: 10,
        unit: "Kaplet",
        durationDays: 3,
        instructions: "Diminum hanya jika sakit kepala berdenyut atau nyeri.",
      },
    ],
    followUpPlan: {
      instruction:
        "Kurangi asupan garam/makanan asin dan kurangi konsumsi kafein. Rutin berolahraga aerobik ringan 30 menit per hari dan tidur cukup 7-8 jam.",
      nextVisitDate: "2026-10-02",
      referredTo: "Poli Penyakit Dalam (Kontrol Rutin Evaluasi Tensi)",
    },
    diagnosticOrders: [
      {
        id: "ord-001-1",
        testCode: "58410-2",
        testName: "Darah Lengkap (CBC)",
        category: "laboratory",
        status: "completed",
        priority: "routine",
        orderDate: "2026-09-02T09:35:00+07:00",
        doctorName: "dr. Rian Pratama, Sp.PD",
        clinicalNotes: "Evaluasi rutin hipertensi dan skrining anemia",
      },
      {
        id: "ord-001-2",
        testCode: "2093-3",
        testName: "Kolesterol Total",
        category: "laboratory",
        status: "completed",
        priority: "routine",
        orderDate: "2026-09-02T09:35:00+07:00",
        doctorName: "dr. Rian Pratama, Sp.PD",
        clinicalNotes: "Skrining profil lipid",
      },
      {
        id: "ord-001-3",
        testCode: "36554-4",
        testName: "Foto Thorax PA",
        category: "radiology",
        status: "completed",
        priority: "routine",
        orderDate: "2026-09-02T09:40:00+07:00",
        doctorName: "dr. Rian Pratama, Sp.PD",
        clinicalNotes: "Evaluasi rasio kardiotorasik (CTR)",
      },
    ],
    labResults: [
      {
        id: "lab-001-1",
        testCode: "58410-2",
        testName: "Hemoglobin",
        category: "Hematologi",
        value: "14.8",
        unit: "g/dL",
        referenceRange: "13.5 - 17.5",
        flag: "normal",
        resultDate: "2026-09-02T10:15:00+07:00",
        performer: "Laboratorium Patologi RSUD",
        notes: "Sampel adekuat, non-hemolisis",
      },
      {
        id: "lab-001-2",
        testCode: "58410-2",
        testName: "Leukosit",
        category: "Hematologi",
        value: "7.400",
        unit: "/µL",
        referenceRange: "4.500 - 11.000",
        flag: "normal",
        resultDate: "2026-09-02T10:15:00+07:00",
        performer: "Laboratorium Patologi RSUD",
      },
      {
        id: "lab-001-3",
        testCode: "58410-2",
        testName: "Trombosit",
        category: "Hematologi",
        value: "285.000",
        unit: "/µL",
        referenceRange: "150.000 - 450.000",
        flag: "normal",
        resultDate: "2026-09-02T10:15:00+07:00",
        performer: "Laboratorium Patologi RSUD",
      },
      {
        id: "lab-001-4",
        testCode: "2093-3",
        testName: "Kolesterol Total",
        category: "Kimia Darah",
        value: "218",
        unit: "mg/dL",
        referenceRange: "< 200",
        flag: "high",
        resultDate: "2026-09-02T10:30:00+07:00",
        performer: "Laboratorium Patologi RSUD",
        notes: "Batas ambang tinggi (Borderline High)",
      },
      {
        id: "lab-001-5",
        testCode: "1558-6",
        testName: "Glukosa Darah Puasa",
        category: "Kimia Darah",
        value: "95",
        unit: "mg/dL",
        referenceRange: "70 - 100",
        flag: "normal",
        resultDate: "2026-09-02T10:30:00+07:00",
        performer: "Laboratorium Patologi RSUD",
      },
    ],
    radiologyResults: [
      {
        id: "rad-001-1",
        examCode: "36554-4",
        examName: "Foto Thorax PA",
        modality: "X-Ray",
        findings: "Cor dan pulmo dalam batas normal. CTR < 50%, sinus dan diafragma lancip. Corakan bronkovaskular normal.",
        conclusion: "Tidak tampak kardiomegali maupun proses spesifik aktif pada paru.",
        radiologistName: "dr. Farhan Malik, Sp.Rad",
        resultDate: "2026-09-02T10:45:00+07:00",
      },
    ],
    addendums: [
      {
        id: "add-001-1",
        timestamp: "2026-09-02T11:00:00+07:00",
        authorName: "dr. Rian Pratama, Sp.PD",
        authorRole: "Dokter Penanggung Jawab Pelayanan (DPJP)",
        noteText: "Pasien telah diedukasi mengenai target tekanan darah < 130/80 mmHg, diet rendah garam (DASH), dan kepatuhan minum obat amlodipine secara teratur.",
      },
    ],
    dischargeDisposition: "Pulang Berobat Jalan (Outpatient)",
    encounterStatus: "in-progress",
    queueNumber: "A-014",
    syncStatus: "pending",
    syncedAt: undefined,
    syncBreakdown: [
      {
        resourceType: "Encounter",
        label: "Kunjungan Rawat Jalan (Encounter)",
        standard: "HL7 FHIR R4",
        status: "synced",
        httpStatus: 200,
        fhirId: "ss-enc-89210-9941a",
      },
      {
        resourceType: "Condition",
        label: "Diagnosis Utama: Hipertensi Primer (I10)",
        standard: "ICD-10",
        status: "synced",
        httpStatus: 201,
        fhirId: "ss-cond-0182-99a",
      },
      {
        resourceType: "Observation",
        label: "Tanda Vital & Antropometri (Vitals)",
        standard: "LOINC",
        status: "synced",
        httpStatus: 201,
        fhirId: "ss-obs-vitals-110",
      },
      {
        resourceType: "Procedure",
        label: "Tindakan: Konsultasi & EKG (89.07, 89.52)",
        standard: "ICD-9-CM",
        status: "synced",
        httpStatus: 201,
        fhirId: "ss-proc-8907-21",
      },
      {
        resourceType: "MedicationRequest",
        label: "Resep Elektronik: Amlodipine 5 mg (KFA)",
        standard: "KFA Kemenkes",
        status: "synced",
        httpStatus: 201,
        fhirId: "ss-med-kfa-881",
      },
    ],
  },
  {
    id: "ENC-20260615-0008",
    registrationNumber: "RJ-20260615-0008",
    patientId: "P-10002891902",
    satusehatEncounterId: "ss-enc-71029-8812c",
    visitDate: "2026-06-15T14:10:00+07:00",
    clinicDepartment: "Poli Umum",
    doctorName: "dr. Amanda Putri, M.Biomed",
    doctorSip: "SIP.446/012/DU/Dinkes/2026",
    doctorIhsId: "N10009842",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Batuk berdahak dan radang tenggorokan 4 hari",
    anamnesis: "Pasien mengeluhkan batuk sejak 4 hari lalu, tenggorokan terasa gatal dan perih saat menelan. Demam sumeng-sumeng pada hari pertama.",
    vitals: {
      systolic: 122,
      diastolic: 80,
      heartRate: 82,
      temperature: 37.4,
      respiratoryRate: 19,
      oxygenSaturation: 99,
      weightKg: 68,
      heightCm: 172,
      bmi: 23.0,
      physicalExamNotes: "Faring hiperemis (+), tonsil T1-T1 tenang, tidak ada eksudat.",
    },
    diagnoses: [
      {
        id: "diag-prev-001-1",
        type: "primary",
        code: "J00",
        display: "Acute nasopharyngitis [common cold]",
        patientFriendlyName: "Faringitis Akut / Radang Saluran Napas Atas",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "resolved",
      },
    ],
    procedures: [
      {
        id: "proc-prev-001-1",
        code: "89.07",
        display: "General medical consultation",
        category: "Konsultasi & Pemeriksaan Fisik",
      },
    ],
    prescriptions: [
      {
        id: "med-prev-001-1",
        kfaCode: "93000551",
        medicationName: "Ambroxol Sirup 15 mg / 5 mL",
        form: "Sirup",
        dosage: "1 sendok takar (5 mL)",
        frequency: "3 x 1 sendok sehari",
        timing: "Sesudah Makan",
        schedule: {
          morning: true,
          afternoon: true,
          evening: true,
        },
        quantity: 1,
        unit: "Botol (60 mL)",
        durationDays: 5,
        instructions: "Kocok dahulu sebelum diminum, habiskan dalam 5 hari.",
      },
      {
        id: "med-prev-001-2",
        kfaCode: "93000889",
        medicationName: "Vitamin C 500 mg",
        form: "Tablet Effervescent",
        dosage: "500 mg",
        frequency: "1 x 1 tablet sehari",
        timing: "Sesudah Makan",
        schedule: {
          morning: true,
        },
        quantity: 10,
        unit: "Tablet",
        durationDays: 10,
        instructions: "Larutkan dalam 200 ml air dingin.",
      },
    ],
    followUpPlan: {
      instruction: "Banyak minum air hangat minimal 2 liter per hari, hindari gorengan dan es.",
    },
    dischargeDisposition: "Pulang Berobat Jalan (Sembuh)",
    encounterStatus: "finished",
    queueNumber: "B-008",
    syncStatus: "synced",
    syncedAt: "2026-06-15T14:45:10+07:00",
  },
];

// Complete Dataset of Pre-seeded Encounters for All Clinic Patients
export const ALL_SAMPLE_ENCOUNTERS: OutpatientEncounter[] = [
  ...MOCK_ENCOUNTERS,
  // 1. Siti Rahmawati (Poli Penyakit Dalam - Dispepsia & Maag)
  {
    id: "ENC-20260902-0002",
    registrationNumber: "RJ-20260902-0002",
    patientId: "P-10004581299",
    satusehatEncounterId: undefined,
    visitDate: "2026-09-02T09:00:00+07:00",
    clinicDepartment: "Poli Penyakit Dalam",
    doctorName: "dr. Rian Pratama, Sp.PD",
    doctorSip: "SIP.446/089/DS/Dinkes/2026",
    doctorIhsId: "N10009841",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Kontrol tensi rutin dan keluhan nyeri ulu hati",
    anamnesis: "Pasien datang dengan keluhan perih dan kembung di ulu hati (epigastrium) sejak 2 hari setelah konsumsi makanan pedas. Riwayat tensi terkontrol baik.",
    vitals: {
      systolic: 125,
      diastolic: 82,
      heartRate: 76,
      temperature: 36.5,
      respiratoryRate: 18,
      oxygenSaturation: 99,
      weightKg: 58,
      heightCm: 160,
      bmi: 22.7,
      physicalExamNotes: "Abdomen: Nyeri tekan epigastrium (+), hepar/lien tidak teraba, bising usus normal.",
    },
    diagnoses: [
      {
        id: "diag-002-1",
        type: "primary",
        code: "K30",
        display: "Functional dyspepsia",
        patientFriendlyName: "Dispepsia Fungsional (Maag / Asam Lambung)",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-002-1",
        code: "89.07",
        display: "General medical consultation",
        category: "Konsultasi & Pemeriksaan Fisik",
        notes: "Edukasi pola diet lambung dan jadwal makan teratur",
      },
    ],
    prescriptions: [
      {
        id: "med-002-1",
        kfaCode: "93000620",
        medicationName: "Omeprazole 20 mg",
        form: "Kapsul",
        dosage: "20 mg",
        frequency: "1 x 1 kapsul sehari",
        timing: "Sebelum Makan",
        schedule: { morning: true },
        quantity: 14,
        unit: "Kapsul",
        durationDays: 14,
        instructions: "Diminum 30 menit sebelum sarapan pagi.",
      },
      {
        id: "med-002-2",
        kfaCode: "93000115",
        medicationName: "Antasida DOEN",
        form: "Tablet Kunyah",
        dosage: "1 tablet",
        frequency: "3 x 1 tablet sehari (Bila Perlu)",
        timing: "Sebelum Makan",
        schedule: { morning: true, afternoon: true, evening: true },
        quantity: 10,
        unit: "Tablet",
        durationDays: 3,
        instructions: "Dikunyah perlahan saat terasa perih di ulu hati.",
      },
    ],
    followUpPlan: {
      instruction: "Makan dalam porsi kecil namun sering, hindari konsumsi kopi, teh pekat, dan cabai.",
      nextVisitDate: "2026-09-16",
      referredTo: "Poli Penyakit Dalam",
    },
    dischargeDisposition: "Pulang Berobat Jalan",
    encounterStatus: "arrived",
    queueNumber: "A-015",
    syncStatus: "pending",
    syncedAt: undefined,
  },
  // 2. H. Ahmad Fauzi (Poli Penyakit Dalam - DM Tipe 2 & Gout)
  {
    id: "ENC-20260902-0003",
    registrationNumber: "RJ-20260902-0003",
    patientId: "P-10007821033",
    satusehatEncounterId: "ss-enc-0902-0003",
    visitDate: "2026-09-02T08:00:00+07:00",
    clinicDepartment: "Poli Penyakit Dalam",
    doctorName: "dr. Rian Pratama, Sp.PD",
    doctorSip: "SIP.446/089/DS/Dinkes/2026",
    doctorIhsId: "N10009841",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Pemeriksaan gula darah puasa dan asam urat rutin",
    anamnesis: "Pasien datang kontrol rutin diabetes mellitus. Rutin minum obat oral. Keluhan kesemutan ekstremitas bawah disangkal.",
    vitals: {
      systolic: 130,
      diastolic: 85,
      heartRate: 80,
      temperature: 36.6,
      respiratoryRate: 20,
      oxygenSaturation: 98,
      weightKg: 72,
      heightCm: 168,
      bmi: 25.5,
      physicalExamNotes: "Ekstremitas hangat, pulsasi arteri tibialis posterior teraba adekuat.",
    },
    diagnoses: [
      {
        id: "diag-003-1",
        type: "primary",
        code: "E11.9",
        display: "Type 2 diabetes mellitus without complications",
        patientFriendlyName: "Diabetes Melitus Tipe 2",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
      {
        id: "diag-003-2",
        type: "secondary",
        code: "M10.9",
        display: "Gout, unspecified",
        patientFriendlyName: "Asam Urat (Gout Artritis)",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-003-1",
        code: "89.07",
        display: "General medical consultation",
        category: "Konsultasi Penyakit Dalam",
      },
    ],
    prescriptions: [
      {
        id: "med-003-1",
        kfaCode: "93000781",
        medicationName: "Metformin HCl 500 mg",
        form: "Tablet",
        dosage: "500 mg",
        frequency: "2 x 1 tablet sehari",
        timing: "Bersama Makanan",
        schedule: { morning: true, evening: true },
        quantity: 60,
        unit: "Tablet",
        durationDays: 30,
        instructions: "Diminum saat makan atau segera sesudah makan.",
      },
      {
        id: "med-003-2",
        kfaCode: "93000910",
        medicationName: "Allopurinol 100 mg",
        form: "Tablet",
        dosage: "100 mg",
        frequency: "1 x 1 tablet sehari",
        timing: "Sesudah Makan",
        schedule: { morning: true },
        quantity: 30,
        unit: "Tablet",
        durationDays: 30,
        instructions: "Diminum pagi hari sesudah makan.",
      },
    ],
    followUpPlan: {
      instruction: "Kurangi konsumsi makanan tinggi purin (jeroan, kacang-kacangan), jaga asupan kalori.",
      nextVisitDate: "2026-10-02",
      referredTo: "Poli Penyakit Dalam",
    },
    dischargeDisposition: "Pulang Berobat Jalan",
    encounterStatus: "finished",
    queueNumber: "A-012",
    syncStatus: "synced",
    syncedAt: "2026-09-02T08:30:00+07:00",
  },
  // 3. Dewi Lestari (Poli Umum - Faringitis Akut)
  {
    id: "ENC-20260902-0004",
    registrationNumber: "RJ-20260902-0004",
    patientId: "P-10009918231",
    satusehatEncounterId: undefined,
    visitDate: "2026-09-02T09:15:00+07:00",
    clinicDepartment: "Poli Umum",
    doctorName: "dr. Amanda Putri, M.Biomed",
    doctorSip: "SIP.446/012/DU/Dinkes/2026",
    doctorIhsId: "N10009842",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Demam sumeng-sumeng dan batuk berdahak 3 hari",
    anamnesis: "Pasien mengeluh badan meriang, tenggorokan perih menelan, dan batuk berdahak sejak 3 hari.",
    vitals: {
      systolic: 118,
      diastolic: 78,
      heartRate: 82,
      temperature: 37.8,
      respiratoryRate: 18,
      oxygenSaturation: 99,
      weightKg: 52,
      heightCm: 158,
      bmi: 20.8,
      physicalExamNotes: "Faring hiperemis (+), tonsil T1/T1 tenang, rhonki (-/-).",
    },
    diagnoses: [
      {
        id: "diag-004-1",
        type: "primary",
        code: "J02.9",
        display: "Acute pharyngitis, unspecified",
        patientFriendlyName: "Radang Tenggorokan Akut (Faringitis)",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-004-1",
        code: "89.07",
        display: "General medical consultation",
        category: "Konsultasi Dokter Umum",
      },
    ],
    prescriptions: [
      {
        id: "med-004-1",
        kfaCode: "93000401",
        medicationName: "Paracetamol 500 mg",
        form: "Kaplet",
        dosage: "500 mg",
        frequency: "3 x 1 kaplet sehari",
        timing: "Sesudah Makan",
        schedule: { morning: true, afternoon: true, evening: true },
        quantity: 10,
        unit: "Kaplet",
        durationDays: 3,
        instructions: "Diminum saat demam atau tenggorokan nyeri.",
      },
      {
        id: "med-004-2",
        kfaCode: "93000551",
        medicationName: "Ambroxol 30 mg",
        form: "Tablet",
        dosage: "30 mg",
        frequency: "3 x 1 tablet sehari",
        timing: "Sesudah Makan",
        schedule: { morning: true, afternoon: true, evening: true },
        quantity: 10,
        unit: "Tablet",
        durationDays: 3,
        instructions: "Diminum sesudah makan untuk mengencerkan dahak.",
      },
    ],
    followUpPlan: {
      instruction: "Istirahat cukup, perbanyak minum air hangat, hindari gorengan dan es.",
      nextVisitDate: "2026-09-07",
      referredTo: "Poli Umum",
    },
    dischargeDisposition: "Pulang Berobat Jalan",
    encounterStatus: "arrived",
    queueNumber: "B-008",
    syncStatus: "pending",
    syncedAt: undefined,
  },
  // 4. Ananda Rizky (Poli Anak - Imunisasi & Tumbuh Kembang)
  {
    id: "ENC-20260902-0005",
    registrationNumber: "RJ-20260902-0005",
    patientId: "P-10003319022",
    satusehatEncounterId: undefined,
    visitDate: "2026-09-02T08:45:00+07:00",
    clinicDepartment: "Poli Anak (Pediatri)",
    doctorName: "dr. Maya Anggraini, Sp.A",
    doctorSip: "SIP.446/033/SPA/Dinkes/2026",
    doctorIhsId: "N10009843",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Imunisasi lanjutan dan evaluasi tumbuh kembang balita",
    anamnesis: "Ibu membawa balita untuk imunisasi rutin dan pemantauan berat serta tinggi badan.",
    vitals: {
      systolic: 100,
      diastolic: 65,
      heartRate: 98,
      temperature: 36.7,
      respiratoryRate: 24,
      oxygenSaturation: 99,
      weightKg: 18,
      heightCm: 105,
      bmi: 16.3,
      physicalExamNotes: "Anak aktif dan ceria, status gizi baik pada kurva pertumbuhan KMS.",
    },
    diagnoses: [
      {
        id: "diag-005-1",
        type: "primary",
        code: "Z00.1",
        display: "Routine child health examination",
        patientFriendlyName: "Pemeriksaan Rutin Kesehatan & Imunisasi Anak",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-005-1",
        code: "99.55",
        display: "Prophylactic administration of vaccine",
        category: "Imunisasi Anak",
      },
    ],
    prescriptions: [
      {
        id: "med-005-1",
        kfaCode: "93000311",
        medicationName: "Paracetamol Drops 100 mg / mL",
        form: "Drops",
        dosage: "0.8 mL",
        frequency: "3 x sehari (Bila Demam)",
        timing: "Sesudah Makan",
        schedule: { morning: true, afternoon: true, evening: true },
        quantity: 1,
        unit: "Botol (15 mL)",
        durationDays: 2,
        instructions: "Diberikan hanya bila timbul demam setelah imunisasi.",
      },
    ],
    followUpPlan: {
      instruction: "Pantau suhu badan 24 jam pasca vaksinasi, berikan ASI dan nutrisi bergizi seimbang.",
      nextVisitDate: "2026-11-10",
      referredTo: "Poli Anak (Pediatri)",
    },
    dischargeDisposition: "Pulang Berobat Jalan",
    encounterStatus: "in-progress",
    queueNumber: "C-005",
    syncStatus: "pending",
    syncedAt: undefined,
  },
  // 5. Hj. Endang Sumarni (Poli Penyakit Dalam - Osteoarthritis Geriatri)
  {
    id: "ENC-20260902-0006",
    registrationNumber: "RJ-20260902-0006",
    patientId: "P-10006719201",
    satusehatEncounterId: undefined,
    visitDate: "2026-09-02T09:20:00+07:00",
    clinicDepartment: "Poli Penyakit Dalam",
    doctorName: "dr. Rian Pratama, Sp.PD",
    doctorSip: "SIP.446/089/DS/Dinkes/2026",
    doctorIhsId: "N10009841",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Nyeri persendian lutut dan osteoartritis kronis (Lansia)",
    anamnesis: "Pasien geriatri mengeluhkan lutut kanan kaku di pagi hari dan nyeri saat berjalan.",
    vitals: {
      systolic: 135,
      diastolic: 85,
      heartRate: 75,
      temperature: 36.4,
      respiratoryRate: 18,
      oxygenSaturation: 98,
      weightKg: 64,
      heightCm: 155,
      bmi: 26.6,
      physicalExamNotes: "Genu dekstra: Krepitasi (+), rentang gerak fleksi terbatas pada 110 derajat.",
    },
    diagnoses: [
      {
        id: "diag-006-1",
        type: "primary",
        code: "M17.9",
        display: "Osteoarthritis of knee, unspecified",
        patientFriendlyName: "Pengapuran Sendi Lutut (Osteoarthritis Genu)",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-006-1",
        code: "89.07",
        display: "General medical consultation",
        category: "Konsultasi Sendi & Geriatri",
      },
    ],
    prescriptions: [
      {
        id: "med-006-1",
        kfaCode: "93000492",
        medicationName: "Glucosamine Sulfate 500 mg",
        form: "Kaplet",
        dosage: "500 mg",
        frequency: "2 x 1 kaplet sehari",
        timing: "Sesudah Makan",
        schedule: { morning: true, evening: true },
        quantity: 60,
        unit: "Kaplet",
        durationDays: 30,
        instructions: "Diminum teratur sesudah makan.",
      },
      {
        id: "med-006-2",
        kfaCode: "93000210",
        medicationName: "Natrium Diklofenak 50 mg",
        form: "Tablet",
        dosage: "50 mg",
        frequency: "2 x 1 tablet sehari (Bila Nyeri)",
        timing: "Sesudah Makan",
        schedule: { morning: true, evening: true },
        quantity: 10,
        unit: "Tablet",
        durationDays: 5,
        instructions: "Diminum sesudah makan hanya bila sendi terasa sangat nyeri.",
      },
    ],
    followUpPlan: {
      instruction: "Lakukan senam lansia aerobik ringan tanpa hentakan, kompres hangat lutut di pagi hari.",
      nextVisitDate: "2026-10-02",
      referredTo: "Poli Penyakit Dalam",
    },
    dischargeDisposition: "Pulang Berobat Jalan",
    encounterStatus: "arrived",
    queueNumber: "A-016",
    syncStatus: "pending",
    syncedAt: undefined,
  },
  // 6. dr. Hendra Setiawan (Poli Gigi - Scaling & Dental Plaque - Opt Out)
  {
    id: "ENC-20260902-0007",
    registrationNumber: "RJ-20260902-0007",
    patientId: "P-10008819209",
    satusehatEncounterId: undefined,
    visitDate: "2026-09-02T09:30:00+07:00",
    clinicDepartment: "Poli Gigi & Mulut",
    doctorName: "drg. Kevin Tanuwidjaja",
    doctorSip: "SIP.446/055/DRG/Dinkes/2026",
    doctorIhsId: "N10009844",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Pembersihan karang gigi (scaling) dan kontrol gigi berlubang",
    anamnesis: "Pasien datang untuk pembersihan karang gigi berkala. Tidak ada keluhan nyeri spontan.",
    vitals: {
      systolic: 120,
      diastolic: 80,
      heartRate: 72,
      temperature: 36.5,
      respiratoryRate: 16,
      oxygenSaturation: 99,
      weightKg: 70,
      heightCm: 175,
      bmi: 22.9,
      physicalExamNotes: "Kalkulus supragingival regio anterior rahang bawah (+).",
    },
    diagnoses: [
      {
        id: "diag-007-1",
        type: "primary",
        code: "K03.6",
        display: "Deposits on teeth",
        patientFriendlyName: "Karang Gigi & Plak Gigi",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-007-1",
        code: "96.54",
        display: "Dental scaling and polishing",
        category: "Tindakan Gigi",
      },
    ],
    prescriptions: [
      {
        id: "med-007-1",
        kfaCode: "93000670",
        medicationName: "Chlorhexidine 0.2% Mouthwash",
        form: "Obat Kumur",
        dosage: "15 mL",
        frequency: "2 x sehari kumur",
        timing: "Sesudah Makan",
        schedule: { morning: true, evening: true },
        quantity: 1,
        unit: "Botol (150 mL)",
        durationDays: 7,
        instructions: "Kumur selama 30 detik setelah menyikat gigi.",
      },
    ],
    followUpPlan: {
      instruction: "Kontrol pembersihan karang gigi berkala setiap 6 bulan sekali.",
      nextVisitDate: "2026-12-10",
      referredTo: "Poli Gigi & Mulut",
    },
    dischargeDisposition: "Pulang Berobat Jalan",
    encounterStatus: "arrived",
    queueNumber: "D-004",
    consentStatus: "opt-out",
    syncStatus: "pending",
  },
  // 7. Rudi Hartono (Poli Jantung - Angina Pectoris CITO)
  {
    id: "ENC-20260902-0008",
    registrationNumber: "RJ-20260902-0008",
    patientId: "P-10005519803",
    satusehatEncounterId: undefined,
    visitDate: "2026-09-02T08:50:00+07:00",
    clinicDepartment: "Poli Jantung & Pembuluh Darah",
    doctorName: "dr. Rian Hidayat, Sp.JP",
    doctorSip: "SIP.446/077/DJ/Dinkes/2026",
    doctorIhsId: "N10009846",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Nyeri dada sebelah kiri tembus ke punggung dan berdebar (CITO)",
    anamnesis: "Pasien mengeluhkan rasa tertekan di dada kiri menjalar ke bahu kiri sejak 1 jam lalu. Keringat dingin (+).",
    vitals: {
      systolic: 145,
      diastolic: 95,
      heartRate: 92,
      temperature: 36.8,
      respiratoryRate: 22,
      oxygenSaturation: 97,
      weightKg: 76,
      heightCm: 170,
      bmi: 26.3,
      physicalExamNotes: "Cor: S1-S2 reguler, tidak ada gallop. EKG: T-inversi lead V4-V6.",
    },
    diagnoses: [
      {
        id: "diag-008-1",
        type: "primary",
        code: "I20.0",
        display: "Unstable angina",
        patientFriendlyName: "Angina Pektoris Tidak Stabil (Nyeri Dada Jantung CITO)",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-008-1",
        code: "89.52",
        display: "Electrocardiogram",
        category: "Pemeriksaan Penunjang Jantung",
        notes: "EKG CITO: Evaluasi iskemia miokard",
      },
    ],
    prescriptions: [
      {
        id: "med-008-1",
        kfaCode: "93000812",
        medicationName: "Isosorbide Dinitrate (ISDN) 5 mg",
        form: "Tablet Sublingual",
        dosage: "5 mg",
        frequency: "1 x 1 tablet (Bila Nyeri Dada)",
        timing: "Sesuai Kebutuhan",
        schedule: { morning: false },
        quantity: 10,
        unit: "Tablet",
        durationDays: 5,
        instructions: "Letakkan di bawah lidah saat dada terasa sesak atau nyeri.",
      },
      {
        id: "med-008-2",
        kfaCode: "93000199",
        medicationName: "Aspirin 80 mg",
        form: "Tablet",
        dosage: "80 mg",
        frequency: "1 x 1 tablet sehari",
        timing: "Sesudah Makan",
        schedule: { morning: true },
        quantity: 30,
        unit: "Tablet",
        durationDays: 30,
        instructions: "Diminum pagi hari sesudah sarapan.",
      },
    ],
    followUpPlan: {
      instruction: "Istirahat total, bila nyeri dada tidak membaik dalam 15 menit segera ke IGD.",
      nextVisitDate: "2026-09-09",
      referredTo: "Poli Jantung & Pembuluh Darah",
    },
    dischargeDisposition: "Pulang Berobat Jalan",
    encounterStatus: "in-progress",
    queueNumber: "E-002",
    syncStatus: "pending",
    syncedAt: undefined,
  },
  // 8. Putri Anggraini (Poli Mata - Konjungtivitis Akut - Opt Out)
  {
    id: "ENC-20260902-0009",
    registrationNumber: "RJ-20260902-0009",
    patientId: "P-10001129481",
    satusehatEncounterId: undefined,
    visitDate: "2026-09-02T09:40:00+07:00",
    clinicDepartment: "Poli Mata",
    doctorName: "dr. Nadia Putri, Sp.M",
    doctorSip: "SIP.446/044/DM/Dinkes/2026",
    doctorIhsId: "N10009847",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Mata merah, berair, dan pandangan silau sejak kemarin",
    anamnesis: "Pasien mengeluh mata kanan merah, berair, dan berpasir setelah terpapar debu jalanan.",
    vitals: {
      systolic: 115,
      diastolic: 75,
      heartRate: 76,
      temperature: 36.5,
      respiratoryRate: 18,
      oxygenSaturation: 99,
      weightKg: 50,
      heightCm: 162,
      bmi: 19.1,
      physicalExamNotes: "OD: Injeksi konjungtiva (+), kornea jernih, sekret serosa.",
    },
    diagnoses: [
      {
        id: "diag-009-1",
        type: "primary",
        code: "H10.9",
        display: "Unspecified conjunctivitis",
        patientFriendlyName: "Konjungtivitis Akut (Iritasi & Radang Mata)",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-009-1",
        code: "95.02",
        display: "Comprehensive ophthalmological examination",
        category: "Pemeriksaan Oftalmologi",
      },
    ],
    prescriptions: [
      {
        id: "med-009-1",
        kfaCode: "93000722",
        medicationName: "Cendo Tobroson Tetes Mata",
        form: "Tetes Mata",
        dosage: "1 tetes",
        frequency: "4 x sehari 1 tetes",
        timing: "Sesuai Kebutuhan",
        schedule: { morning: true, afternoon: true, evening: true, night: true },
        quantity: 1,
        unit: "Botol (5 mL)",
        durationDays: 5,
        instructions: "Teteskan pada mata kanan yang merah, jangan mengucek mata.",
      },
    ],
    followUpPlan: {
      instruction: "Hindari mengucek mata, gunakan kacamata pelindung dari debu.",
      nextVisitDate: "2026-09-09",
      referredTo: "Poli Mata",
    },
    dischargeDisposition: "Pulang Berobat Jalan",
    encounterStatus: "arrived",
    queueNumber: "F-003",
    consentStatus: "opt-out",
    syncStatus: "pending",
  },
  // 9. Opa Soetrisno (Poli Penyakit Dalam - BPH & Hipertensi)
  {
    id: "ENC-20260902-0010",
    registrationNumber: "RJ-20260902-0010",
    patientId: "P-10004491023",
    satusehatEncounterId: undefined,
    visitDate: "2026-09-02T09:50:00+07:00",
    clinicDepartment: "Poli Penyakit Dalam",
    doctorName: "dr. Rian Pratama, Sp.PD",
    doctorSip: "SIP.446/089/DS/Dinkes/2026",
    doctorIhsId: "N10009841",
    hospitalName: "RS Umum Daerah Sehat Sejahtera",
    hospitalOrgId: "10000004",
    chiefComplaint: "Kontrol rutin diabetes melitus dan cek HbA1c (Lansia)",
    anamnesis: "Pasien lansia kontrol rutin. Mengeluh sering buang air kecil malam hari dan tensi batas atas.",
    vitals: {
      systolic: 148,
      diastolic: 88,
      heartRate: 74,
      temperature: 36.5,
      respiratoryRate: 18,
      oxygenSaturation: 98,
      weightKg: 62,
      heightCm: 165,
      bmi: 22.8,
      physicalExamNotes: "Abdomen: Buli tidak distensi, ekstremitas hangat.",
    },
    diagnoses: [
      {
        id: "diag-010-1",
        type: "primary",
        code: "N40",
        display: "Hyperplasia of prostate",
        patientFriendlyName: "Pembesaran Prostat Jinak (BPH)",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
      {
        id: "diag-010-2",
        type: "secondary",
        code: "I10",
        display: "Essential (primary) hypertension",
        patientFriendlyName: "Hipertensi Derajat 2",
        system: "http://hl7.org/fhir/sid/icd-10",
        clinicalStatus: "active",
      },
    ],
    procedures: [
      {
        id: "proc-010-1",
        code: "89.07",
        display: "General medical consultation",
        category: "Konsultasi Geriatri",
      },
    ],
    prescriptions: [
      {
        id: "med-010-1",
        kfaCode: "93000830",
        medicationName: "Tamsulosin HCl 0.4 mg",
        form: "Kapsul",
        dosage: "0.4 mg",
        frequency: "1 x 1 kapsul sehari",
        timing: "Sesudah Makan",
        schedule: { night: true },
        quantity: 30,
        unit: "Kapsul",
        durationDays: 30,
        instructions: "Diminum malam hari 30 menit sesudah makan malam.",
      },
      {
        id: "med-010-2",
        kfaCode: "93000182",
        medicationName: "Amlodipine Besilate 10 mg",
        form: "Tablet",
        dosage: "10 mg",
        frequency: "1 x 1 tablet sehari",
        timing: "Sesudah Makan",
        schedule: { night: true },
        quantity: 30,
        unit: "Tablet",
        durationDays: 30,
        instructions: "Diminum malam hari sesudah makan.",
      },
    ],
    followUpPlan: {
      instruction: "Batasi minum air menjelang tidur malam, kontrol berkala.",
      nextVisitDate: "2026-10-02",
      referredTo: "Poli Penyakit Dalam",
    },
    dischargeDisposition: "Pulang Berobat Jalan",
    encounterStatus: "arrived",
    queueNumber: "A-017",
    syncStatus: "pending",
    syncedAt: undefined,
  },
];

// Sample database of registered patients across the clinic
export const SAMPLE_PATIENTS: PatientProfile[] = [
  {
    id: "P-10002891902",
    nik: "3174051208820003",
    mrn: "RM-2026-08912",
    name: "Budi Santoso, S.Kom",
    gender: "male",
    birthDate: "1982-08-12",
    phone: "0812-8941-2099",
    address: "Jl. Margonda Raya No. 45, Beji, Depok",
    bloodType: "O",
    allergies: ["Penisilin (Gatal-gatal & Ruam Kulit)"],
    emergencyContact: {
      name: "Ratna Kusuma (Istri)",
      relation: "Istri",
      phone: "0813-7721-9988",
    },
    paymentPayer: "BPJS Kesehatan (JKN-PBI)",
    lastVisitDate: "2026-08-25",
    lastVisitDepartment: "Poli Penyakit Dalam",
    lastVisitDoctor: "dr. Rian Pratama, Sp.PD",
    lastVisitDiagnosis: "Hipertensi Primer (I10)",
    totalVisitsCount: 6,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10004581299",
    nik: "3275025503900004",
    mrn: "RM-2026-09144",
    name: "Siti Rahmawati, S.Pd",
    gender: "female",
    birthDate: "1990-03-15",
    phone: "0856-1122-3344",
    address: "Jl. Pemuda No. 12, Rawamangun, Jakarta Timur",
    bloodType: "A",
    allergies: ["Sulfa / Kotrimoksazol"],
    emergencyContact: {
      name: "Bambang Wijaya (Suami)",
      relation: "Suami",
      phone: "0818-9988-7766",
    },
    paymentPayer: "BPJS Kesehatan (Non-PBI)",
    lastVisitDate: "2026-08-18",
    lastVisitDepartment: "Poli Penyakit Dalam",
    lastVisitDoctor: "dr. Rian Pratama, Sp.PD",
    lastVisitDiagnosis: "Dispepsia Fungsional (K30)",
    totalVisitsCount: 3,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10007821033",
    nik: "3171010101780002",
    mrn: "RM-2026-07823",
    name: "H. Ahmad Fauzi",
    gender: "male",
    birthDate: "1978-01-01",
    phone: "0811-9876-5432",
    address: "Jl. Cikini Raya No. 88, Menteng, Jakarta Pusat",
    bloodType: "B",
    allergies: [],
    emergencyContact: {
      name: "Nurul Hidayah (Anak)",
      relation: "Anak Kandung",
      phone: "0812-3344-5566",
    },
    paymentPayer: "BPJS Kesehatan (JKN-PBI)",
    lastVisitDate: "2026-08-02",
    lastVisitDepartment: "Poli Penyakit Dalam",
    lastVisitDoctor: "dr. Rian Pratama, Sp.PD",
    lastVisitDiagnosis: "Diabetes Mellitus Tipe 2 (E11.9)",
    totalVisitsCount: 12,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10009918231",
    nik: "3175084409890001",
    mrn: "RM-2026-06719",
    name: "Dewi Lestari",
    gender: "female",
    birthDate: "1989-09-04",
    phone: "0812-4455-6677",
    address: "Jl. Otista Raya No. 10, Jakarta Timur",
    bloodType: "B",
    allergies: [],
    emergencyContact: {
      name: "Agus Pratama",
      relation: "Suami",
      phone: "0813-9988-1122",
    },
    paymentPayer: "Mandiri / Pasien Umum",
    lastVisitDate: "2026-07-15",
    lastVisitDepartment: "Poli Umum",
    lastVisitDoctor: "dr. Amanda Putri, M.Biomed",
    lastVisitDiagnosis: "Faringitis Akut (J02.9)",
    totalVisitsCount: 2,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10003319022",
    nik: "3173016205180005",
    mrn: "RM-2026-03112",
    name: "Ananda Rizky",
    gender: "male",
    birthDate: "2018-05-22",
    phone: "0817-6655-4433",
    address: "Jl. Tebet Barat No. 8, Jakarta Selatan",
    bloodType: "A",
    allergies: ["Kacang"],
    emergencyContact: {
      name: "Ibu Dian",
      relation: "Ibu Kandung",
      phone: "0817-6655-4433",
    },
    paymentPayer: "BPJS Kesehatan (JKN-PBI)",
    lastVisitDate: "2026-06-10",
    lastVisitDepartment: "Poli Anak (Pediatri)",
    lastVisitDoctor: "dr. Maya Anggraini, Sp.A",
    lastVisitDiagnosis: "Imunisasi & Tumbuh Kembang",
    totalVisitsCount: 5,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10006719201",
    nik: "3172021508600002",
    mrn: "RM-2026-04519",
    name: "Hj. Endang Sumarni",
    gender: "female",
    birthDate: "1960-08-15",
    phone: "0813-8822-1100",
    address: "Jl. Boulevard Kelapa Gading No. 14, Jakarta Utara",
    bloodType: "O",
    allergies: ["Aspirin"],
    emergencyContact: {
      name: "Indra (Anak)",
      relation: "Anak Kandung",
      phone: "0813-8822-1100",
    },
    paymentPayer: "BPJS Kesehatan (JKN-PBI)",
    lastVisitDate: "2026-05-20",
    lastVisitDepartment: "Poli Penyakit Dalam",
    lastVisitDoctor: "dr. Rian Pratama, Sp.PD",
    lastVisitDiagnosis: "Osteoarthritis Genu (M17.9)",
    totalVisitsCount: 8,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10008819209",
    nik: "3175091212950007",
    mrn: "RM-2026-09941",
    name: "dr. Hendra Setiawan",
    gender: "male",
    birthDate: "1995-12-12",
    phone: "0819-2233-4455",
    address: "Jl. Kayu Putih Tengah No. 20, Jakarta Timur",
    bloodType: "AB",
    allergies: [],
    emergencyContact: {
      name: "dr. Maya",
      relation: "Istri",
      phone: "0819-2233-4455",
    },
    paymentPayer: "Asuransi Swasta (Prudential)",
    lastVisitDate: "2026-02-11",
    lastVisitDepartment: "Poli Umum",
    lastVisitDoctor: "dr. Amanda Putri, M.Biomed",
    lastVisitDiagnosis: "Medical Check-Up Eksekutif",
    totalVisitsCount: 1,
    satusehatConsent: "opt-out",
  },
  {
    id: "P-10005519803",
    nik: "3276014402750004",
    mrn: "RM-2026-05612",
    name: "Rudi Hartono",
    gender: "male",
    birthDate: "1975-02-14",
    phone: "0857-9900-1122",
    address: "Jl. Cinere Raya No. 99, Depok",
    bloodType: "O",
    allergies: [],
    emergencyContact: {
      name: "Yanti (Istri)",
      relation: "Istri",
      phone: "0857-9900-1122",
    },
    paymentPayer: "BPJS Kesehatan (JKN-PBI)",
    lastVisitDate: "2026-08-10",
    lastVisitDepartment: "Poli Jantung & Pembuluh Darah",
    lastVisitDoctor: "dr. Rian Hidayat, Sp.JP",
    lastVisitDiagnosis: "Angina Pectoris Unstable (I20.0)",
    totalVisitsCount: 4,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10001129481",
    nik: "3174095509990008",
    mrn: "RM-2026-01290",
    name: "Putri Anggraini",
    gender: "female",
    birthDate: "1999-09-15",
    phone: "0821-4455-9988",
    address: "Jl. Fatmawati No. 33, Jakarta Selatan",
    bloodType: "B",
    allergies: ["Seafood"],
    emergencyContact: {
      name: "Pak Anggoro",
      relation: "Ayah",
      phone: "0821-4455-9988",
    },
    paymentPayer: "Mandiri / Pasien Umum",
    lastVisitDate: "2025-11-20",
    lastVisitDepartment: "Poli Mata",
    lastVisitDoctor: "dr. Nadia Putri, Sp.M",
    lastVisitDiagnosis: "Miopia Ringan (H52.1)",
    totalVisitsCount: 2,
    satusehatConsent: "opt-out",
  },
  {
    id: "P-10004491023",
    nik: "3173052204550001",
    mrn: "RM-2026-08102",
    name: "Opa Soetrisno",
    gender: "male",
    birthDate: "1955-04-22",
    phone: "0812-7711-2233",
    address: "Jl. Tomang Raya No. 5, Jakarta Barat",
    bloodType: "A",
    allergies: [],
    emergencyContact: {
      name: "Sari (Anak)",
      relation: "Anak Kandung",
      phone: "0812-7711-2233",
    },
    paymentPayer: "BPJS Kesehatan (JKN-PBI)",
    lastVisitDate: "2026-08-28",
    lastVisitDepartment: "Poli Penyakit Dalam",
    lastVisitDoctor: "dr. Rian Pratama, Sp.PD",
    lastVisitDiagnosis: "BPH & Hipertensi Tingkat 2",
    totalVisitsCount: 15,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10009128374",
    nik: "3276024108980002",
    mrn: "RM-2026-09201",
    name: "drg. Cindy Permata, Sp.Ort",
    gender: "female",
    birthDate: "1998-08-21",
    phone: "0813-9900-3311",
    address: "Jl. Senopati No. 40, Kebayoran Baru, Jakarta Selatan",
    bloodType: "AB",
    allergies: ["Lateks"],
    emergencyContact: {
      name: "dr. Kevin",
      relation: "Suami",
      phone: "0813-9900-3311",
    },
    paymentPayer: "Asuransi Swasta (Allianz)",
    lastVisitDate: "2026-08-05",
    lastVisitDepartment: "Poli Mata",
    lastVisitDoctor: "dr. Nadia Putri, Sp.M",
    lastVisitDiagnosis: "Astigmatisme Miopia (H52.2)",
    totalVisitsCount: 3,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10006281940",
    nik: "3174081504150003",
    mrn: "RM-2026-02488",
    name: "Kenzo Al-Ghifari",
    gender: "male",
    birthDate: "2020-04-15",
    phone: "0812-3344-9988",
    address: "Jl. Kemang Timur No. 19, Mampang, Jakarta Selatan",
    bloodType: "O",
    allergies: ["Amoksisilin"],
    emergencyContact: {
      name: "Ghifari (Ayah)",
      relation: "Ayah Kandung",
      phone: "0812-3344-9988",
    },
    paymentPayer: "BPJS Kesehatan (JKN-PBI)",
    lastVisitDate: "2026-08-14",
    lastVisitDepartment: "Poli Anak (Pediatri)",
    lastVisitDoctor: "dr. Maya Anggraini, Sp.A",
    lastVisitDiagnosis: "Rinofaringitis Akut (Common Cold)",
    totalVisitsCount: 4,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10007391822",
    nik: "3171051907720005",
    mrn: "RM-2026-07319",
    name: "Bambang Hermanto",
    gender: "male",
    birthDate: "1972-07-19",
    phone: "0816-5544-3322",
    address: "Jl. Kramat Raya No. 55, Senen, Jakarta Pusat",
    bloodType: "B",
    allergies: [],
    emergencyContact: {
      name: "Sri Rahayu (Istri)",
      relation: "Istri",
      phone: "0816-5544-3322",
    },
    paymentPayer: "Mandiri / Pasien Umum",
    lastVisitDate: "2026-08-22",
    lastVisitDepartment: "Poli Gigi & Mulut",
    lastVisitDoctor: "drg. Kevin Tanuwidjaja",
    lastVisitDiagnosis: "Pulpitis Irreversibel Gigi 36 (K04.0)",
    totalVisitsCount: 3,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10008492011",
    nik: "3275086203920001",
    mrn: "RM-2026-08490",
    name: "Maya Indah Lestari",
    gender: "female",
    birthDate: "1992-03-22",
    phone: "0858-7711-8899",
    address: "Jl. Galaxy Raya No. 8, Jaka Setia, Bekasi Selatan",
    bloodType: "A",
    allergies: [],
    emergencyContact: {
      name: "Rian (Kakak)",
      relation: "Kakak Kandung",
      phone: "0858-7711-8899",
    },
    paymentPayer: "BPJS Kesehatan (Non-PBI)",
    totalVisitsCount: 0,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10009581029",
    nik: "3175061405800003",
    mrn: "RM-2026-09511",
    name: "Eko Prasetyo, S.T.",
    gender: "male",
    birthDate: "1980-05-14",
    phone: "0812-9988-4411",
    address: "Jl. Duren Sawit Indah No. 12, Jakarta Timur",
    bloodType: "O",
    allergies: [],
    emergencyContact: {
      name: "Dini (Istri)",
      relation: "Istri",
      phone: "0812-9988-4411",
    },
    paymentPayer: "Mandiri / Pasien Umum",
    totalVisitsCount: 0,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10001928471",
    nik: "3172085109860002",
    mrn: "RM-2026-01994",
    name: "Nur Aini Wijayanti",
    gender: "female",
    birthDate: "1986-09-11",
    phone: "0813-2244-6688",
    address: "Jl. Sunter Agung Tengah No. 22, Tanjung Priok, Jakarta Utara",
    bloodType: "B",
    allergies: ["Kliping Logam / Nikel"],
    emergencyContact: {
      name: "Fauzan (Suami)",
      relation: "Suami",
      phone: "0813-2244-6688",
    },
    paymentPayer: "BPJS Kesehatan (JKN-PBI)",
    lastVisitDate: "2026-07-28",
    lastVisitDepartment: "Poli Umum",
    lastVisitDoctor: "dr. Amanda Putri, M.Biomed",
    lastVisitDiagnosis: "Gastritis Akut Erosif (K29.1)",
    totalVisitsCount: 7,
    satusehatConsent: "opt-in",
  },
  {
    id: "P-10009988112",
    nik: "3171051508770005",
    mrn: "RM-2026-09981",
    name: "Bambang Soediro (Rawat Inap)",
    gender: "male",
    birthDate: "1977-08-15",
    phone: "0812-9988-7711",
    address: "Jl. Kramat Raya No. 41, Senen, Jakarta Pusat",
    bloodType: "O",
    allergies: [],
    emergencyContact: {
      name: "Sri Rahayu (Istri)",
      relation: "Istri",
      phone: "0812-9988-7711",
    },
    paymentPayer: "BPJS Kesehatan (Non-PBI)",
    totalVisitsCount: 9,
    satusehatConsent: "opt-in",
    patientStatus: "inpatient",
    inpatientDetails: {
      room: "Bangsal Dahlia (Lt. 4)",
      bed: "Bed 03-A",
      admissionDate: "2026-09-20",
      dpjp: "dr. Rian Pratama, Sp.PD",
    },
  },
  {
    id: "P-10009988334",
    nik: "3171050201400001",
    mrn: "RM-2026-00042",
    name: "Alm. Sastrowardoyo (Meninggal)",
    gender: "male",
    birthDate: "1940-01-02",
    phone: "0811-0000-1111",
    address: "Jl. Pegangsaan Timur No. 10, Jakarta Pusat",
    bloodType: "AB",
    allergies: [],
    emergencyContact: {
      name: "Keluarga Alm.",
      relation: "Ahli Waris",
      phone: "0811-0000-1111",
    },
    paymentPayer: "Mandiri / Pasien Umum",
    totalVisitsCount: 14,
    satusehatConsent: "opt-in",
    patientStatus: "deceased",
  },
];

// Initial Live Worklist of Registered Patients Today in FIFO Order (Earliest Arrival First)
export const INITIAL_WORKLIST: ClinicQueuePatientItem[] = [
  {
    id: "Q-001",
    registrationNumber: "RJ-20260913-0001",
    queueNumber: "A-012",
    patient: SAMPLE_PATIENTS[2], // H. Ahmad Fauzi (08:00 WIB)
    department: "Poli Penyakit Dalam",
    doctor: "dr. Rian Pratama, Sp.PD",
    room: "Ruang 204 (Lt. 2)",
    arrivalTime: "08:00 WIB",
    arrivalTimestamp: 1725411600000,
    chiefComplaint: "Pemeriksaan gula darah puasa dan asam urat rutin",
    status: "finished" as const,
    satusehatStatus: "synced" as const,
    satusehatConsent: "opt-in" as const,
    triagePriority: "regular" as const,
  },
  {
    id: "Q-002",
    registrationNumber: "RJ-20260913-0002",
    queueNumber: "A-014",
    patient: SAMPLE_PATIENTS[0], // Budi Santoso (08:30 WIB)
    department: "Poli Penyakit Dalam",
    doctor: "dr. Rian Pratama, Sp.PD",
    room: "Ruang 204 (Lt. 2)",
    arrivalTime: "08:30 WIB",
    arrivalTimestamp: 1725413400000,
    chiefComplaint: "Sakit kepala di tengkuk belakang sejak 3 hari dan badan terasa cepat lelah",
    status: "in-progress" as const,
    satusehatStatus: "pending" as const,
    satusehatConsent: "opt-in" as const,
    triagePriority: "regular" as const,
  },
  {
    id: "Q-003",
    registrationNumber: "RJ-20260913-0003",
    queueNumber: "C-005",
    patient: SAMPLE_PATIENTS[4], // Ananda Rizky (08:45 WIB)
    department: "Poli Anak (Pediatri)",
    doctor: "dr. Maya Anggraini, Sp.A",
    room: "Ruang 105 (Lt. 1)",
    arrivalTime: "08:45 WIB",
    arrivalTimestamp: 1725414300000,
    chiefComplaint: "Imunisasi lanjutan dan evaluasi tumbuh kembang balita",
    status: "in-progress" as const,
    satusehatStatus: "pending" as const,
    satusehatConsent: "opt-in" as const,
    triagePriority: "pediatric" as const,
  },
  {
    id: "Q-004",
    registrationNumber: "RJ-20260913-0004",
    queueNumber: "E-002",
    patient: SAMPLE_PATIENTS[7], // Rudi Hartono (CITO)
    department: "Poli Jantung & Pembuluh Darah",
    doctor: "dr. Rian Hidayat, Sp.JP",
    room: "Ruang 208 (Lt. 2)",
    arrivalTime: "08:50 WIB",
    arrivalTimestamp: 1725414600000,
    chiefComplaint: "Nyeri dada sebelah kiri tembus ke punggung dan berdebar (CITO)",
    status: "in-progress" as const,
    satusehatStatus: "pending" as const,
    satusehatConsent: "opt-in" as const,
    triagePriority: "urgent" as const,
  },
  {
    id: "Q-005",
    registrationNumber: "RJ-20260913-0005",
    queueNumber: "A-015",
    patient: SAMPLE_PATIENTS[1], // Siti Rahmawati (09:00 WIB)
    department: "Poli Penyakit Dalam",
    doctor: "dr. Rian Pratama, Sp.PD",
    room: "Ruang 204 (Lt. 2)",
    arrivalTime: "09:00 WIB",
    arrivalTimestamp: 1725415200000,
    chiefComplaint: "Kontrol tensi rutin dan keluhan nyeri ulu hati",
    status: "arrived" as const,
    satusehatStatus: "pending" as const,
    satusehatConsent: "opt-in" as const,
    triagePriority: "regular" as const,
  },
  {
    id: "Q-006",
    registrationNumber: "RJ-20260913-0006",
    queueNumber: "B-008",
    patient: SAMPLE_PATIENTS[3], // Dewi Lestari (09:15 WIB)
    department: "Poli Umum",
    doctor: "dr. Amanda Putri, M.Biomed",
    room: "Ruang 102 (Lt. 1)",
    arrivalTime: "09:15 WIB",
    arrivalTimestamp: 1725416100000,
    chiefComplaint: "Demam sumeng-sumeng dan batuk berdahak 3 hari",
    status: "arrived" as const,
    satusehatStatus: "pending" as const,
    satusehatConsent: "opt-in" as const,
    triagePriority: "regular" as const,
  },
  {
    id: "Q-007",
    registrationNumber: "RJ-20260913-0007",
    queueNumber: "A-016",
    patient: SAMPLE_PATIENTS[5], // Hj. Endang Sumarni (Geriatri)
    department: "Poli Penyakit Dalam",
    doctor: "dr. Rian Pratama, Sp.PD",
    room: "Ruang 204 (Lt. 2)",
    arrivalTime: "09:20 WIB",
    arrivalTimestamp: 1725416400000,
    chiefComplaint: "Nyeri persendian lutut dan osteoartritis kronis (Lansia)",
    status: "arrived" as const,
    satusehatStatus: "pending" as const,
    satusehatConsent: "opt-in" as const,
    triagePriority: "geriatric" as const,
  },
  {
    id: "Q-008",
    registrationNumber: "RJ-20260913-0008",
    queueNumber: "D-004",
    patient: SAMPLE_PATIENTS[6], // dr. Hendra Setiawan (Gigi - Opt-Out)
    department: "Poli Gigi & Mulut",
    doctor: "drg. Kevin Tanuwidjaja",
    room: "Ruang 201 (Lt. 2)",
    arrivalTime: "09:30 WIB",
    arrivalTimestamp: 1725417000000,
    chiefComplaint: "Pembersihan karang gigi (scaling) dan kontrol gigi berlubang",
    status: "arrived" as const,
    satusehatStatus: "pending" as const,
    satusehatConsent: "opt-out" as const,
    triagePriority: "regular" as const,
  },
  {
    id: "Q-009",
    registrationNumber: "RJ-20260913-0009",
    queueNumber: "F-003",
    patient: SAMPLE_PATIENTS[8], // Putri Anggraini (Mata - Opt-Out)
    department: "Poli Mata",
    doctor: "dr. Nadia Putri, Sp.M",
    room: "Ruang 210 (Lt. 2)",
    arrivalTime: "09:40 WIB",
    arrivalTimestamp: 1725417600000,
    chiefComplaint: "Mata merah, berair, dan pandangan silau sejak kemarin",
    status: "arrived" as const,
    satusehatStatus: "pending" as const,
    satusehatConsent: "opt-out" as const,
    triagePriority: "regular" as const,
  },
  {
    id: "Q-010",
    registrationNumber: "RJ-20260913-0010",
    queueNumber: "A-017",
    patient: SAMPLE_PATIENTS[9], // Opa Soetrisno (Geriatri)
    department: "Poli Penyakit Dalam",
    doctor: "dr. Rian Pratama, Sp.PD",
    room: "Ruang 204 (Lt. 2)",
    arrivalTime: "09:50 WIB",
    arrivalTimestamp: 1725418200000,
    chiefComplaint: "Kontrol rutin diabetes melitus dan cek HbA1c (Lansia)",
    status: "arrived" as const,
    satusehatStatus: "pending" as const,
    satusehatConsent: "opt-in" as const,
    triagePriority: "geriatric" as const,
  },
];

